[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Scheduled functions use this configuration
[functions]
  node_bundler = "esbuild"

# Redirect for the app to handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Set up proxy for CoinDesk RSS feed to avoid CORS issues
[[redirects]]
  from = "/coindesk-rss-proxy"
  to = "/.netlify/functions/coindesk-rss-proxy"
  status = 200

# Set up proxies for Supabase functions
[[redirects]]
  from = "/api/coindesk-news"
  to = "https://kxfdmpfigwhyvglrukwm.supabase.co/functions/v1/fetch-coindesk-news"
  status = 200
  force = true
  headers = {Authorization = "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt4ZmRtcGZpZ3doeXZnbHJ1a3dtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxODQzMDAsImV4cCI6MjA2MDc2MDMwMH0.xkKUtB65Vo4btKQWDxKdf2DAtM1NmCmZg9WEL63xpvQ"}

[[redirects]]
  from = "/api/crypto-news"
  to = "https://kxfdmpfigwhyvglrukwm.supabase.co/functions/v1/fetch-crypto-news"
  status = 200
  force = true
  headers = {Authorization = "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt4ZmRtcGZpZ3doeXZnbHJ1a3dtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxODQzMDAsImV4cCI6MjA2MDc2MDMwMH0.xkKUtB65Vo4btKQWDxKdf2DAtM1NmCmZg9WEL63xpvQ"}

[[redirects]]
  from = "/api/cryptopanic-news"
  to = "https://kxfdmpfigwhyvglrukwm.supabase.co/functions/v1/fetch-cryptopanic-news"
  status = 200
  force = true
  headers = {Authorization = "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt4ZmRtcGZpZ3doeXZnbHJ1a3dtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxODQzMDAsImV4cCI6MjA2MDc2MDMwMH0.xkKUtB65Vo4btKQWDxKdf2DAtM1NmCmZg9WEL63xpvQ"}

[[redirects]]
  from = "/api/firecrawl-news"
  to = "https://kxfdmpfigwhyvglrukwm.supabase.co/functions/v1/fetch-firecrawl-news"
  status = 200
  force = true
  headers = {Authorization = "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt4ZmRtcGZpZ3doeXZnbHJ1a3dtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxODQzMDAsImV4cCI6MjA2MDc2MDMwMH0.xkKUtB65Vo4btKQWDxKdf2DAtM1NmCmZg9WEL63xpvQ"}

[[redirects]]
  from = "/api/aggregate-news"
  to = "https://kxfdmpfigwhyvglrukwm.supabase.co/functions/v1/aggregate-news"
  status = 200
  force = true
  headers = {Authorization = "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt4ZmRtcGZpZ3doeXZnbHJ1a3dtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxODQzMDAsImV4cCI6MjA2MDc2MDMwMH0.xkKUtB65Vo4btKQWDxKdf2DAtM1NmCmZg9WEL63xpvQ"}

[[redirects]]
  from = "/api/crypto-crawler"
  to = "https://kxfdmpfigwhyvglrukwm.supabase.co/functions/v1/supadata-crypto-crawler"
  status = 200
  force = true
  headers = {Authorization = "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt4ZmRtcGZpZ3doeXZnbHJ1a3dtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxODQzMDAsImV4cCI6MjA2MDc2MDMwMH0.xkKUtB65Vo4btKQWDxKdf2DAtM1NmCmZg9WEL63xpvQ"}

[[redirects]]
  from = "/api/update-crypto-settings"
  to = "https://kxfdmpfigwhyvglrukwm.supabase.co/functions/v1/update-crypto-settings"
  status = 200
  force = true
  headers = {Authorization = "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt4ZmRtcGZpZ3doeXZnbHJ1a3dtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxODQzMDAsImV4cCI6MjA2MDc2MDMwMH0.xkKUtB65Vo4btKQWDxKdf2DAtM1NmCmZg9WEL63xpvQ"}

# Configure the Fetch Feeds plugin
[[plugins]]
  package = "netlify-plugin-fetch-feeds"

  [plugins.inputs]
    dataDir = "public/feeds"

    [[plugins.inputs.feeds]]
      name = "reuters-topnews"
      url = "https://rss.app/feeds/_LGUsXhQQjR11Xad5.xml"
      ttl = 3600  # Re-fetch every hour
      
    [[plugins.inputs.feeds]]
      name = "coindesk-rss"
      url = "https://www.coindesk.com/arc/outboundfeeds/rss/"
      ttl = 3600  # Re-fetch every hour
      
    [[plugins.inputs.feeds]]
      name = "impact-news"
      url = "https://rss.app/feeds/v1.1/_odXmUWvOS88olvY1.json"
      ttl = 3600  # Re-fetch every hour