[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Scheduled functions use this configuration
[functions]
  node_bundler = "esbuild"

# Redirect for the app to handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configure the Fetch Feeds plugin
[[plugins]]
  package = "netlify-plugin-fetch-feeds"

  [plugins.inputs]
    dataDir = "public/feeds"

    [[plugins.inputs.feeds]]
      name = "reuters-topnews"
      url = "http://feeds.reuters.com/reuters/topNews"
      ttl = 3600  # Re-fetch every hour